const ActionTypes = {

	FETCH_CONSUMER_PLAN:"FETCH_CONSUMER_PLAN",
	GET_CONSUMER_PLAN:"GET_CONSUMER_PLAN",
	FETCH_CONSUMER_PLAN_FAILED:"FETCH_CONSUMER_PLAN_FAILED",
	
	FETCH_RECIPES:"FETCH_RECIPES",
	GET_RECIPES:"GET_RECIPES",
	FETCH_RECIPES_FAILED:"FETCH_RECIPES_FAILED",
	
	FETCH_GROCERIES:"FETCH_GROCERIES",
	GET_GROCERIES:"GET_GROCERIES",
	FETCH_GROCERIES_FAILED:"FETCH_GROCERIES_FAILED",
	
	FETCH_CONSUMER_NOTES:"FETCH_CONSUMER_NOTES",
	GET_CONSUMER_NOTES:"GET_CONSUMER_NOTES",
	FETCH_CONSUMER_NOTES_FAILED:"FETCH_CONSUMER_NOTES_FAILED",
	
	REQUEST_CONSUMER_ORDERS:"REQUEST_CONSUMER_ORDERS",
	GET_CONSUMER_ORDERS:"GET_CONSUMER_ORDERS",
	REQUEST_CONSUMER_ORDERS_FAILED:"REQUEST_CONSUMER_ORDERS_FAILED",
	
	GET_SHOPPING_LIST:"GET_SHOPPING_LIST"
	
}; 

export default ActionTypes;